import { describe, it, expect } from 'vitest';

/**
 * Integration Tests for Clinical Trials Search with Phase Filtering
 * 
 * Bug: Trials that don't match the clinical PHASE in the user query are being included
 * 
 * Architecture:
 * User Query → gatherSearchResults → enhance-search (REAL Gemini API) → search-clinical-trials (REAL ClinicalTrials.gov API)
 * 
 * Test queries:
 * - "Alzheimer's drugs in Phase 2 trials"
 * - "GLP-1 oral drugs in Phase 3 trials"
 * 
 * Note: These are INTEGRATION TESTS that call REAL APIs:
 * - Gemini API for search enhancement
 * - ClinicalTrials.gov for trial data
 * 
 * Requires:
 * - GOOGLE_GEMINI_API_KEY environment variable
 * - Internet connection
 */

describe('Clinical Trials Search - Phase Filtering Integration Tests', () => {

  it('should generate Phase 2 queries and return only Phase 2 trials for Alzheimer\'s', async () => {
    const userQuery = "Alzheimer's drugs in Phase 2 trials";

    // Import and call the real service (no mocks)
    const { GatherSearchResultsService } = await import('../src/services/gatherSearchResults');
    const result = await GatherSearchResultsService.gatherSearchResults(userQuery);

    // Get the search strategies that were generated by the LLM
    const strategies = result.searchStrategies;
    expect(strategies).toBeDefined();
    expect(strategies.length).toBeGreaterThan(0);

    console.log(`\n📋 User Query: "${userQuery}"`);
    console.log(`\n🔍 LLM Generated ${strategies.length} Search Strategies:`);
    strategies.forEach((s, i) => {
      console.log(`  ${i + 1}. "${s.strategy.query}" (${s.count} trials)`);
    });

    // Verify that ALL generated queries include "Phase 2"
    const queriesWithoutPhase2 = strategies.filter(strategyResult => 
      !strategyResult.strategy.query.toLowerCase().includes('phase 2')
    );

    if (queriesWithoutPhase2.length > 0) {
      console.error('\n❌ BUG DETECTED: Some queries missing "Phase 2":');
      queriesWithoutPhase2.forEach(s => {
        console.error(`  - "${s.strategy.query}"`);
      });
    }

    expect(queriesWithoutPhase2.length).toBe(0);

    // Verify results from the REAL ClinicalTrials.gov API
    console.log(`\n📊 Total Trials Retrieved: ${result.trials.length}`);

    if (result.trials.length > 0) {
      // Check phase distribution
      const phaseDistribution = new Map<string, number>();
      result.trials.forEach(trial => {
        if (trial.phase) {
          trial.phase.forEach((p: string) => {
            phaseDistribution.set(p, (phaseDistribution.get(p) || 0) + 1);
          });
        }
      });

      console.log('\n📈 Phase Distribution:');
      phaseDistribution.forEach((count, phase) => {
        console.log(`  ${phase}: ${count} trials`);
      });

      // Find trials that don't include Phase 2
      const trialsNotPhase2 = result.trials.filter(trial => 
        !trial.phase || !trial.phase.some((p: string) => p.includes('Phase 2'))
      );

      if (trialsNotPhase2.length > 0) {
        console.error(`\n❌ BUG: ${trialsNotPhase2.length} trials without Phase 2:`);
        trialsNotPhase2.slice(0, 5).forEach(trial => {
          console.error(`  - ${trial.nctId}: ${trial.briefTitle}`);
          console.error(`    Phases: ${trial.phase?.join(', ') || 'None'}`);
        });
      }

      // All trials should include Phase 2
      const allTrialsArePhase2 = result.trials.every(trial => 
        trial.phase && trial.phase.some((p: string) => p.includes('Phase 2'))
      );

      expect(allTrialsArePhase2).toBe(true);
      console.log('\n✅ All trials are Phase 2 or include Phase 2');
    } else {
      console.log('\n⚠️  No trials found (may be due to API or query specificity)');
    }
  }, 60000); // 60 second timeout for real API calls

  it('should generate Phase 3 queries and return only Phase 3 trials for GLP-1', async () => {
    const userQuery = "GLP-1 oral drugs in Phase 3 trials";

    const { GatherSearchResultsService } = await import('../src/services/gatherSearchResults');
    const result = await GatherSearchResultsService.gatherSearchResults(userQuery);

    const strategies = result.searchStrategies;
    expect(strategies).toBeDefined();
    expect(strategies.length).toBeGreaterThan(0);

    console.log(`\n📋 User Query: "${userQuery}"`);
    console.log(`\n🔍 LLM Generated ${strategies.length} Search Strategies:`);
    strategies.forEach((s, i) => {
      console.log(`  ${i + 1}. "${s.strategy.query}" (${s.count} trials)`);
    });

    // Verify that ALL generated queries include "Phase 3"
    const queriesWithoutPhase3 = strategies.filter(strategyResult => 
      !strategyResult.strategy.query.toLowerCase().includes('phase 3')
    );

    if (queriesWithoutPhase3.length > 0) {
      console.error('\n❌ BUG DETECTED: Some queries missing "Phase 3":');
      queriesWithoutPhase3.forEach(s => {
        console.error(`  - "${s.strategy.query}"`);
      });
    }

    expect(queriesWithoutPhase3.length).toBe(0);

    console.log(`\n📊 Total Trials Retrieved: ${result.trials.length}`);

    if (result.trials.length > 0) {
      const phaseDistribution = new Map<string, number>();
      result.trials.forEach(trial => {
        if (trial.phase) {
          trial.phase.forEach((p: string) => {
            phaseDistribution.set(p, (phaseDistribution.get(p) || 0) + 1);
          });
        }
      });

      console.log('\n📈 Phase Distribution:');
      phaseDistribution.forEach((count, phase) => {
        console.log(`  ${phase}: ${count} trials`);
      });

      // Find trials that don't include Phase 3
      const trialsNotPhase3 = result.trials.filter(trial => 
        !trial.phase || !trial.phase.some((p: string) => p.includes('Phase 3'))
      );

      if (trialsNotPhase3.length > 0) {
        console.error(`\n❌ BUG: ${trialsNotPhase3.length} trials without Phase 3:`);
        trialsNotPhase3.slice(0, 5).forEach(trial => {
          console.error(`  - ${trial.nctId}: ${trial.briefTitle}`);
          console.error(`    Phases: ${trial.phase?.join(', ') || 'None'}`);
        });
      }

      // All trials should include Phase 3 (or Phase 2/3 combinations)
      const allTrialsArePhase3 = result.trials.every(trial => 
        trial.phase && trial.phase.some((p: string) => p.includes('Phase 3'))
      );

      expect(allTrialsArePhase3).toBe(true);
      console.log('\n✅ All trials are Phase 3 or include Phase 3');
    } else {
      console.log('\n⚠️  No trials found (may be due to API or query specificity)');
    }
  }, 60000);

  it('should generate diverse queries when no phase is specified', async () => {
    const userQuery = "GLP-1 drugs";

    const { GatherSearchResultsService } = await import('../src/services/gatherSearchResults');
    const result = await GatherSearchResultsService.gatherSearchResults(userQuery);

    const strategies = result.searchStrategies;
    expect(strategies).toBeDefined();
    expect(strategies.length).toBeGreaterThan(0);

    console.log(`\n📋 User Query: "${userQuery}" (no phase specified)`);
    console.log(`\n🔍 LLM Generated ${strategies.length} Search Strategies:`);
    strategies.forEach((s, i) => {
      console.log(`  ${i + 1}. "${s.strategy.query}" (${s.count} trials)`);
    });

    // When no phase is specified, queries should be diverse (not all containing the same phase)
    const phase1Queries = strategies.filter(s => s.strategy.query.toLowerCase().includes('phase 1')).length;
    const phase2Queries = strategies.filter(s => s.strategy.query.toLowerCase().includes('phase 2')).length;
    const phase3Queries = strategies.filter(s => s.strategy.query.toLowerCase().includes('phase 3')).length;
    const noPhaseQueries = strategies.filter(s => 
      !s.strategy.query.toLowerCase().includes('phase 1') &&
      !s.strategy.query.toLowerCase().includes('phase 2') &&
      !s.strategy.query.toLowerCase().includes('phase 3') &&
      !s.strategy.query.toLowerCase().includes('phase 4')
    ).length;

    console.log(`\n📊 Query Diversity:`);
    console.log(`  Phase 1: ${phase1Queries} queries`);
    console.log(`  Phase 2: ${phase2Queries} queries`);
    console.log(`  Phase 3: ${phase3Queries} queries`);
    console.log(`  No phase: ${noPhaseQueries} queries`);

    // Not all queries should be the same phase
    const notAllSamePhase = !(phase1Queries === strategies.length || 
                              phase2Queries === strategies.length || 
                              phase3Queries === strategies.length);
    
    expect(notAllSamePhase).toBe(true);

    if (result.trials.length > 0) {
      // Results should include trials from multiple phases
      const phases = new Set(result.trials.flatMap(t => t.phase || []));
      console.log(`\n📈 Trials span ${phases.size} different phases:`, Array.from(phases).join(', '));
      
      // Should have diversity in phases
      expect(phases.size).toBeGreaterThan(0);
      console.log('\n✅ Query diversity confirmed - not constrained to single phase');
    }
  }, 60000);

  it('should verify LLM respects phase requirements in user query', async () => {
    const testCases = [
      { query: "Alzheimer's drugs in Phase 2 trials", expectedPhase: "phase 2" },
      { query: "GLP-1 drugs in Phase 3", expectedPhase: "phase 3" },
      { query: "Phase 1 cancer immunotherapy", expectedPhase: "phase 1" },
    ];

    console.log('\n🧪 Testing LLM Phase Awareness Across Multiple Queries:\n');

    for (const testCase of testCases) {
      console.log(`\n📋 Query: "${testCase.query}"`);
      console.log(`   Expected: All queries should include "${testCase.expectedPhase}"`);

      const { GatherSearchResultsService } = await import('../src/services/gatherSearchResults');
      const result = await GatherSearchResultsService.gatherSearchResults(testCase.query);

      const strategies = result.searchStrategies;
      const queriesWithPhase = strategies.filter(s => 
        s.strategy.query.toLowerCase().includes(testCase.expectedPhase)
      );

      console.log(`   Result: ${queriesWithPhase.length}/${strategies.length} queries include "${testCase.expectedPhase}"`);
      
      if (queriesWithPhase.length < strategies.length) {
        const missingPhase = strategies.filter(s => 
          !s.strategy.query.toLowerCase().includes(testCase.expectedPhase)
        );
        console.log(`   ❌ Missing phase in:`);
        missingPhase.forEach(s => console.log(`      - "${s.strategy.query}"`));
      } else {
        console.log(`   ✅ All queries correctly include "${testCase.expectedPhase}"`);
      }

      expect(queriesWithPhase.length).toBe(strategies.length);
    }
  }, 180000); // 3 minutes for multiple test cases
});
