-- Migration: Add pipeline_candidates column to projects table
-- Created: 2025-11-27
-- Purpose: Store AI-extracted asset development pipeline candidates for each project
--          This allows preserving pipeline data when switching between projects

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS pipeline_candidates JSONB DEFAULT NULL;

COMMENT ON COLUMN projects.pipeline_candidates IS 'AI-extracted pipeline drug candidates. Array of PipelineDrugCandidate objects generated by LLM from drug groups';

-- Create GIN index for efficient JSONB queries
CREATE INDEX IF NOT EXISTS idx_projects_pipeline_candidates_gin ON projects USING GIN (pipeline_candidates);

